import { mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { afterEach, beforeEach, describe, expect, test } from "bun:test";

import {
  checkIntegrity,
  enrichEcosystems,
  loadLock,
  mergeLock,
  verifyIntegrity,
  writeLock,
} from "../src/lock.js";
import type { LockEntry, LockUpdate, MidoLock } from "../src/lock.js";

let tmpDir: string;

function makeEntry(range: string, ecosystems: readonly string[] = ["typescript"]): LockEntry {
  // Compute integrity the same way the module does
  const { createHash } = require("node:crypto");
  const hash = createHash("sha256").update(range).digest("hex").slice(0, 16);
  return {
    range,
    integrity: `sha256-${hash}`,
    ecosystems: [...ecosystems],
    resolvedAt: "2026-03-26T00:00:00.000Z",
  };
}

function makeLock(entries: Record<string, string>): MidoLock {
  const resolved: Record<string, LockEntry> = {};
  for (const [name, range] of Object.entries(entries)) {
    resolved[name] = makeEntry(range);
  }
  return { version: 2, resolved };
}

beforeEach(() => {
  tmpDir = mkdtempSync(join(tmpdir(), "mido-lock-test-"));
});

afterEach(() => {
  rmSync(tmpDir, { recursive: true, force: true });
});

describe("loadLock", () => {
  test("returns null when mido.lock file is absent", async () => {
    const result = await loadLock(tmpDir);
    expect(result).toBeNull();
  });

  test("returns null on malformed YAML", async () => {
    writeFileSync(join(tmpDir, "mido.lock"), "{ broken yaml: [unclosed", "utf-8");
    const result = await loadLock(tmpDir);
    expect(result).toBeNull();
  });

  test("returns null when YAML does not match expected schema", async () => {
    writeFileSync(join(tmpDir, "mido.lock"), "unrelated: data\n", "utf-8");
    const result = await loadLock(tmpDir);
    expect(result).toBeNull();
  });

  test("returns parsed V2 lock when file is valid", async () => {
    const lock = makeLock({ zod: "^3.0.0", yaml: "^2.0.0" });
    await writeLock(tmpDir, lock);
    const result = await loadLock(tmpDir);
    expect(result).not.toBeNull();
    expect(result?.version).toBe(2);
    expect(result?.resolved["zod"]?.range).toBe("^3.0.0");
    expect(result?.resolved["yaml"]?.range).toBe("^2.0.0");
  });

  test("migrates V1 lock (flat ranges) to V2 on load", async () => {
    const v1Content = `resolved:\n  zod: "^3.0.0"\n  yaml: "^2.0.0"\n`;
    writeFileSync(join(tmpDir, "mido.lock"), v1Content, "utf-8");
    const result = await loadLock(tmpDir);
    expect(result).not.toBeNull();
    expect(result?.version).toBe(2);
    expect(result?.resolved["zod"]?.range).toBe("^3.0.0");
    expect(result?.resolved["zod"]?.ecosystems).toEqual(["unknown"]);
    expect(result?.resolved["zod"]?.integrity).toContain("sha256-");

    // V1 lock should have been rewritten as V2 on disk
    const raw = readFileSync(join(tmpDir, "mido.lock"), "utf-8");
    expect(raw).toContain("version: 2");
  });
});

describe("writeLock", () => {
  test("writes lock file and round-trips correctly", async () => {
    const lock = makeLock({ zod: "^3.0.0" });
    await writeLock(tmpDir, lock);
    const result = await loadLock(tmpDir);
    expect(result?.resolved["zod"]?.range).toBe("^3.0.0");
  });

  test("writes keys alphabetically", async () => {
    const lock = makeLock({ zod: "^3.0.0", axios: "^1.0.0", micromatch: "^4.0.0" });
    await writeLock(tmpDir, lock);

    const content = readFileSync(join(tmpDir, "mido.lock"), "utf-8");
    const axiosPos = content.indexOf("axios");
    const micromatchPos = content.indexOf("micromatch");
    const zodPos = content.indexOf("zod:");
    expect(axiosPos).toBeLessThan(micromatchPos);
    expect(micromatchPos).toBeLessThan(zodPos);
  });

  test("overwrites existing lock file", async () => {
    await writeLock(tmpDir, makeLock({ zod: "^2.0.0" }));
    await writeLock(tmpDir, makeLock({ zod: "^3.0.0" }));
    const result = await loadLock(tmpDir);
    expect(result?.resolved["zod"]?.range).toBe("^3.0.0");
  });

  test("includes version and header", async () => {
    await writeLock(tmpDir, makeLock({ zod: "^3.0.0" }));
    const content = readFileSync(join(tmpDir, "mido.lock"), "utf-8");
    expect(content).toContain("version: 2");
    expect(content).toContain("Auto-generated by mido");
  });
});

describe("mergeLock", () => {
  test("creates new lock from empty", () => {
    const updates: LockUpdate[] = [
      { depName: "zod", range: "^3.0.0", ecosystems: ["typescript"] },
    ];
    const result = mergeLock(null, updates);
    expect(result.version).toBe(2);
    expect(result.resolved["zod"]?.range).toBe("^3.0.0");
    expect(result.resolved["zod"]?.ecosystems).toEqual(["typescript"]);
  });

  test("merges ecosystems from existing entry", () => {
    const existing = makeLock({ zod: "^3.0.0" });
    const updates: LockUpdate[] = [
      { depName: "zod", range: "^3.0.0", ecosystems: ["dart"] },
    ];
    const result = mergeLock(existing, updates);
    expect(result.resolved["zod"]?.ecosystems).toContain("typescript");
    expect(result.resolved["zod"]?.ecosystems).toContain("dart");
  });

  test("new entries override existing range", () => {
    const existing = makeLock({ zod: "^2.0.0" });
    const updates: LockUpdate[] = [
      { depName: "zod", range: "^3.0.0", ecosystems: ["typescript"] },
    ];
    const result = mergeLock(existing, updates);
    expect(result.resolved["zod"]?.range).toBe("^3.0.0");
  });
});

describe("integrity", () => {
  test("verifyIntegrity returns true for valid entry", () => {
    const entry = makeEntry("^3.0.0");
    expect(verifyIntegrity(entry)).toBe(true);
  });

  test("verifyIntegrity returns false for tampered entry", () => {
    const entry = { ...makeEntry("^3.0.0"), integrity: "sha256-tampered" };
    expect(verifyIntegrity(entry)).toBe(false);
  });

  test("checkIntegrity returns empty array for valid lock", () => {
    const lock = makeLock({ zod: "^3.0.0", yaml: "^2.0.0" });
    expect(checkIntegrity(lock)).toEqual([]);
  });

  test("checkIntegrity returns tampered dep names", () => {
    const lock = makeLock({ zod: "^3.0.0" });
    lock.resolved["zod"] = { ...lock.resolved["zod"]!, integrity: "sha256-bad" };
    const violations = checkIntegrity(lock);
    expect(violations).toEqual(["zod"]);
  });
});

describe("enrichEcosystems", () => {
  test("replaces unknown ecosystems with graph data", () => {
    // Simulate a V1-migrated lock where ecosystems default to ["unknown"]
    const lock = makeLock({ zod: "^3.0.0" });
    lock.resolved["zod"] = { ...lock.resolved["zod"]!, ecosystems: ["unknown"] };

    const depEcosystems = new Map<string, readonly string[]>([
      ["zod", ["typescript", "dart"]],
    ]);

    const enriched = enrichEcosystems(lock, depEcosystems);
    expect(enriched.resolved["zod"]?.ecosystems).toEqual(["typescript", "dart"]);
  });

  test("preserves already-known ecosystems", () => {
    const lock = makeLock({ zod: "^3.0.0" });
    // ecosystems already set to ["typescript"] by makeLock — not ["unknown"]
    const depEcosystems = new Map<string, readonly string[]>([
      ["zod", ["dart"]],
    ]);

    const enriched = enrichEcosystems(lock, depEcosystems);
    // Should not overwrite — entry already has known ecosystem
    expect(enriched.resolved["zod"]?.ecosystems).toEqual(["typescript"]);
    // Should return the same reference when nothing changed
    expect(enriched).toBe(lock);
  });

  test("leaves unknown when graph has no data for dependency", () => {
    const lock = makeLock({ zod: "^3.0.0" });
    lock.resolved["zod"] = { ...lock.resolved["zod"]!, ecosystems: ["unknown"] };

    // Graph has no entry for zod
    const depEcosystems = new Map<string, readonly string[]>();

    const enriched = enrichEcosystems(lock, depEcosystems);
    expect(enriched.resolved["zod"]?.ecosystems).toEqual(["unknown"]);
    expect(enriched).toBe(lock);
  });
});
