import { mkdtempSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { afterEach, beforeEach, describe, expect, test } from 'bun:test';

import { loadLock, writeLock } from '../src/lock.js';

let tmpDir: string;

beforeEach(() => {
  tmpDir = mkdtempSync(join(tmpdir(), 'mido-lock-test-'));
});

afterEach(() => {
  rmSync(tmpDir, { recursive: true, force: true });
});

describe('loadLock', () => {
  test('returns null when mido.lock file is absent', async () => {
    const result = await loadLock(tmpDir);
    expect(result).toBeNull();
  });

  test('returns null on malformed YAML', async () => {
    writeFileSync(join(tmpDir, 'mido.lock'), '{ broken yaml: [unclosed', 'utf-8');
    const result = await loadLock(tmpDir);
    expect(result).toBeNull();
  });

  test('returns null when YAML does not match expected schema', async () => {
    writeFileSync(join(tmpDir, 'mido.lock'), 'unrelated: data\n', 'utf-8');
    const result = await loadLock(tmpDir);
    expect(result).toBeNull();
  });

  test('returns parsed lock when file is valid', async () => {
    const content = `resolved:\n  zod: "^3.0.0"\n  yaml: "^2.0.0"\n`;
    writeFileSync(join(tmpDir, 'mido.lock'), content, 'utf-8');
    const result = await loadLock(tmpDir);
    expect(result).not.toBeNull();
    expect(result?.resolved['zod']).toBe('^3.0.0');
    expect(result?.resolved['yaml']).toBe('^2.0.0');
  });

  test('returns parsed lock with header comment present', async () => {
    const content = `# Auto-generated by mido check --fix\n\nresolved:\n  zod: "^3.0.0"\n`;
    writeFileSync(join(tmpDir, 'mido.lock'), content, 'utf-8');
    const result = await loadLock(tmpDir);
    expect(result).not.toBeNull();
    expect(result?.resolved['zod']).toBe('^3.0.0');
  });
});

describe('writeLock', () => {
  test('writes lock file to the correct path', async () => {
    const lock = { resolved: { zod: '^3.0.0' } };
    await writeLock(tmpDir, lock);

    const result = await loadLock(tmpDir);
    expect(result).not.toBeNull();
    expect(result?.resolved['zod']).toBe('^3.0.0');
  });

  test('writes keys alphabetically', async () => {
    const lock = {
      resolved: {
        zod: '^3.0.0',
        axios: '^1.0.0',
        micromatch: '^4.0.0',
      },
    };
    await writeLock(tmpDir, lock);

    const { readFileSync } = await import('node:fs');
    const content = readFileSync(join(tmpDir, 'mido.lock'), 'utf-8');

    const axiosPos = content.indexOf('axios');
    const micromatchPos = content.indexOf('micromatch');
    const zodPos = content.indexOf('zod');

    expect(axiosPos).toBeLessThan(micromatchPos);
    expect(micromatchPos).toBeLessThan(zodPos);
  });

  test('overwrites existing lock file', async () => {
    await writeLock(tmpDir, { resolved: { zod: '^2.0.0' } });
    await writeLock(tmpDir, { resolved: { zod: '^3.0.0' } });

    const result = await loadLock(tmpDir);
    expect(result?.resolved['zod']).toBe('^3.0.0');
  });

  test('round-trips correctly through write then load', async () => {
    const original = {
      resolved: {
        a: '^1.0.0',
        b: '^2.0.0',
        c: '^3.0.0',
      },
    };

    await writeLock(tmpDir, original);
    const loaded = await loadLock(tmpDir);

    expect(loaded?.resolved['a']).toBe('^1.0.0');
    expect(loaded?.resolved['b']).toBe('^2.0.0');
    expect(loaded?.resolved['c']).toBe('^3.0.0');
  });
});
