import type { ValidatedTokens } from "../design/types.js";
import { resolveExtensions } from "../design/types.js";

const HEADER = `/* GENERATED BY MIDO — DO NOT EDIT */`;

/**
 * Convert camelCase to kebab-case.
 */
function camelToKebab(str: string): string {
  return str.replace(/[A-Z]/g, (letter) => `-${letter.toLowerCase()}`);
}

/**
 * Generate CSS custom properties with light/dark theme support.
 * Light values in :root, dark overrides in [data-theme="dark"].
 */
export function generateCSS(tokens: ValidatedTokens): string {
  const lines: string[] = [HEADER, ""];

  const lightVars: string[] = [];
  const darkVars: string[] = [];

  // ColorScheme
  lightVars.push("  /* ColorScheme — light */");
  darkVars.push("  /* ColorScheme — dark */");

  for (const [key, entry] of Object.entries(tokens.color)) {
    const varName = `--color-${camelToKebab(key)}`;
    lightVars.push(`  ${varName}: ${entry.light};`);
    darkVars.push(`  ${varName}: ${entry.dark};`);
  }

  // Extensions
  const extensions = resolveExtensions(tokens.extensions);
  for (const ext of extensions) {
    lightVars.push("");
    lightVars.push(`  /* Extensions — ${ext.name} light */`);
    darkVars.push("");
    darkVars.push(`  /* Extensions — ${ext.name} dark */`);

    for (const [, field] of ext.fields) {
      const varName = `--${ext.getter}-${camelToKebab(field.name)}`;

      switch (field.type) {
        case "color": {
          const v = field.value as { readonly light: string; readonly dark: string };
          lightVars.push(`  ${varName}: ${v.light};`);
          darkVars.push(`  ${varName}: ${v.dark};`);
          break;
        }
        case "color-static": {
          lightVars.push(`  ${varName}: ${field.value as string};`);
          darkVars.push(`  ${varName}: ${field.value as string};`);
          break;
        }
        case "number": {
          lightVars.push(`  ${varName}: ${field.value as number}px;`);
          darkVars.push(`  ${varName}: ${field.value as number}px;`);
          break;
        }
        case "number-themed": {
          const v = field.value as { readonly light: number; readonly dark: number };
          lightVars.push(`  ${varName}: ${v.light}px;`);
          darkVars.push(`  ${varName}: ${v.dark}px;`);
          break;
        }
        case "string": {
          lightVars.push(`  ${varName}: ${field.value as string};`);
          darkVars.push(`  ${varName}: ${field.value as string};`);
          break;
        }
      }
    }
  }

  // Spacing
  if (tokens.spacing) {
    lightVars.push("");
    lightVars.push("  /* Spacing */");
    for (const [key, value] of Object.entries(tokens.spacing)) {
      lightVars.push(`  --spacing-${camelToKebab(key)}: ${value}px;`);
    }
  }

  // Radius
  if (tokens.radius) {
    lightVars.push("");
    lightVars.push("  /* Radius */");
    for (const [key, value] of Object.entries(tokens.radius)) {
      const unit = value >= 999 ? "" : "px";
      lightVars.push(`  --radius-${camelToKebab(key)}: ${value}${unit};`);
    }
  }

  // Icon size
  if (tokens.iconSize) {
    lightVars.push("");
    lightVars.push("  /* Icon size */");
    for (const [key, value] of Object.entries(tokens.iconSize)) {
      lightVars.push(`  --icon-${camelToKebab(key)}: ${value}px;`);
    }
  }

  lines.push(":root {");
  lines.push(...lightVars);
  lines.push("}");
  lines.push("");
  lines.push('[data-theme="dark"] {');
  lines.push(...darkVars);
  lines.push("}");
  lines.push("");

  return lines.join("\n");
}

/**
 * Generate TypeScript constants for numeric tokens.
 */
export function generateTS(tokens: ValidatedTokens): string {
  const lines: string[] = [HEADER, ""];

  if (tokens.spacing) {
    lines.push("export const DSSpacing = {");
    for (const [key, value] of Object.entries(tokens.spacing)) {
      lines.push(`  ${key}: ${value},`);
    }
    lines.push("} as const;");
    lines.push("");
  }

  if (tokens.radius) {
    lines.push("export const DSRadius = {");
    for (const [key, value] of Object.entries(tokens.radius)) {
      lines.push(`  ${key}: ${value},`);
    }
    lines.push("} as const;");
    lines.push("");
  }

  if (tokens.iconSize) {
    lines.push("export const DSIconSize = {");
    for (const [key, value] of Object.entries(tokens.iconSize)) {
      lines.push(`  ${key}: ${value},`);
    }
    lines.push("} as const;");
    lines.push("");
  }

  // Type exports
  if (tokens.spacing) {
    lines.push("export type DSSpacingKey = keyof typeof DSSpacing;");
  }
  if (tokens.radius) {
    lines.push("export type DSRadiusKey = keyof typeof DSRadius;");
  }
  if (tokens.iconSize) {
    lines.push("export type DSIconSizeKey = keyof typeof DSIconSize;");
  }
  lines.push("");

  return lines.join("\n");
}
