import { readFileSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, test } from "bun:test";

import { validateTokens } from "../../src/plugins/builtin/design/token-schema.js";
import type { ValidatedTokens } from "../../src/plugins/builtin/design/types.js";
import { generateCSS, generateTS } from "../../src/plugins/builtin/typescript/token-codegen.js";

const FIXTURE_PATH = join(import.meta.dir, "..", "fixture-tokens", "tokens.json");

function loadTokens(): ValidatedTokens {
  const raw = JSON.parse(readFileSync(FIXTURE_PATH, "utf-8"));
  const result = validateTokens(raw);
  if (!result.data) {
    throw new Error(`Fixture tokens invalid: ${result.errors.map((e) => e.message).join(", ")}`);
  }
  return result.data;
}

describe("generateCSS", () => {
  test("produces valid CSS with :root and dark theme", () => {
    const output = generateCSS(loadTokens());
    expect(output).toContain("GENERATED BY MIDO");
    expect(output).toContain(":root {");
    expect(output).toContain('[data-theme="dark"]');
  });

  test("generates color scheme variables", () => {
    const output = generateCSS(loadTokens());
    expect(output).toContain("--color-primary: #B25134;");
    expect(output).toContain("--color-on-primary: #FAF9F5;");
  });

  test("generates dark-mode color overrides", () => {
    const output = generateCSS(loadTokens());
    const darkSection = output.split('[data-theme="dark"]')[1];
    expect(darkSection).toContain("--color-primary: #E07B5A;");
  });

  test("generates extension CSS variables with getter prefix", () => {
    const output = generateCSS(loadTokens());
    expect(output).toContain("--extended-brand:");
    expect(output).toContain("--genre-fantasy:");
  });

  test("generates spacing variables including zero", () => {
    const output = generateCSS(loadTokens());
    expect(output).toContain("--spacing-none: 0px;");
    expect(output).toContain("--spacing-xs: 4px;");
  });

  test("generates radius variables", () => {
    const output = generateCSS(loadTokens());
    expect(output).toContain("--radius-sm: 2px;");
    expect(output).toContain("--radius-full: 9999;");
  });

  test("generates icon size variables", () => {
    const output = generateCSS(loadTokens());
    expect(output).toContain("--icon-xs: 18px;");
    expect(output).toContain("--icon-hero: 120px;");
  });
});

describe("generateTS", () => {
  test("produces valid TypeScript with as const", () => {
    const output = generateTS(loadTokens());
    expect(output).toContain("GENERATED BY MIDO");
    expect(output).toContain("as const;");
  });

  test("generates DSSpacing with zero", () => {
    const output = generateTS(loadTokens());
    expect(output).toContain("export const DSSpacing = {");
    expect(output).toContain("none: 0,");
    expect(output).toContain("xs: 4,");
  });

  test("generates DSRadius", () => {
    const output = generateTS(loadTokens());
    expect(output).toContain("export const DSRadius = {");
    expect(output).toContain("full: 9999,");
  });

  test("generates DSIconSize", () => {
    const output = generateTS(loadTokens());
    expect(output).toContain("export const DSIconSize = {");
    expect(output).toContain("hero: 120,");
  });

  test("generates type exports", () => {
    const output = generateTS(loadTokens());
    expect(output).toContain("export type DSSpacingKey = keyof typeof DSSpacing;");
    expect(output).toContain("export type DSRadiusKey = keyof typeof DSRadius;");
    expect(output).toContain("export type DSIconSizeKey = keyof typeof DSIconSize;");
  });
});
