import { readFileSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, test } from "bun:test";

import { validateTokens } from "../../src/plugins/builtin/design/token-schema.js";
import type { ValidatedTokens } from "../../src/plugins/builtin/design/types.js";
import {
  generateBarrel,
  generateColorScheme,
  generateConstants,
  generatePackageBarrel,
  generateTheme,
  generateThemeExtensions,
} from "../../src/plugins/builtin/dart/token-codegen.js";

const FIXTURE_PATH = join(import.meta.dir, "..", "fixture-tokens", "tokens.json");

function loadTokens(): ValidatedTokens {
  const raw = JSON.parse(readFileSync(FIXTURE_PATH, "utf-8"));
  const result = validateTokens(raw);
  if (!result.data) {
    throw new Error(`Fixture tokens invalid: ${result.errors.map((e) => e.message).join(", ")}`);
  }
  return result.data;
}

describe("generateColorScheme", () => {
  test("produces valid Dart with M3 color roles", () => {
    const output = generateColorScheme(loadTokens());
    expect(output).toContain("GENERATED BY MIDO");
    expect(output).toContain("abstract final class GeneratedColorScheme");
    expect(output).toContain("static ColorScheme get light");
    expect(output).toContain("static ColorScheme get dark");
    expect(output).toContain("primary:");
    expect(output).toContain("onPrimary:");
    expect(output).toContain("surface:");
    expect(output).toContain("Color(0xFF");
  });

  test("uses const ColorScheme constructor", () => {
    const output = generateColorScheme(loadTokens());
    expect(output).toContain("const ColorScheme.light(");
    expect(output).toContain("const ColorScheme.dark(");
  });
});

describe("generateThemeExtensions", () => {
  test("generates one class per custom section", () => {
    const output = generateThemeExtensions(loadTokens());
    expect(output).toContain("class Extended extends ThemeExtension<Extended>");
    expect(output).toContain("class Genre extends ThemeExtension<Genre>");
  });

  test("includes @immutable, copyWith, lerp, light/dark statics", () => {
    const output = generateThemeExtensions(loadTokens());
    expect(output).toContain("@immutable");
    expect(output).toContain("copyWith");
    expect(output).toContain("lerp");
    expect(output).toContain("Color.lerp");
    expect(output).toContain("static const light = Extended(");
    expect(output).toContain("static const dark = Extended(");
  });

  test("handles rgba() colors with Color.fromRGBO", () => {
    const output = generateThemeExtensions(loadTokens());
    expect(output).toContain("Color.fromRGBO(");
  });

  test("all fields are Color type", () => {
    const output = generateThemeExtensions(loadTokens());
    expect(output).toContain("final Color brand;");
    expect(output).toContain("final Color fantasy;");
  });
});

describe("generateConstants", () => {
  test("generates DSSpacing with zero value", () => {
    const output = generateConstants(loadTokens());
    expect(output).toContain("abstract final class DSSpacing");
    expect(output).toContain("static const double none = 0;");
    expect(output).toContain("static const double xs = 4;");
  });

  test("generates DSRadius with large value", () => {
    const output = generateConstants(loadTokens());
    expect(output).toContain("abstract final class DSRadius");
    expect(output).toContain("static const double full = 9999;");
  });

  test("generates DSElevation", () => {
    const output = generateConstants(loadTokens());
    expect(output).toContain("abstract final class DSElevation");
    expect(output).toContain("static const double none = 0;");
  });

  test("generates DSShadow with empty arrays for none", () => {
    const output = generateConstants(loadTokens());
    expect(output).toContain("abstract final class DSShadow");
    // Empty shadow array still has opening/closing brackets
    expect(output).toContain("static const List<BoxShadow> none = [");
    // Verify it's there (the array is empty, so no BoxShadow entries)
    expect(output).not.toContain("none = [\n    BoxShadow(");
  });

  test("generates DSIconSize", () => {
    const output = generateConstants(loadTokens());
    expect(output).toContain("abstract final class DSIconSize");
    expect(output).toContain("static const double hero = 120;");
  });
});

describe("generateTheme", () => {
  test("generates AppTheme with light/dark", () => {
    const output = generateTheme(loadTokens(), "test_design");
    expect(output).toContain("abstract final class AppTheme");
    expect(output).toContain("static final ThemeData light");
    expect(output).toContain("static final ThemeData dark");
  });

  test("generates ThemeContextExtension with extension getters", () => {
    const output = generateTheme(loadTokens(), "test_design");
    expect(output).toContain("Extended get extended");
    expect(output).toContain("Genre get genre");
  });

  test("generates text style shortcuts", () => {
    const output = generateTheme(loadTokens(), "test_design");
    expect(output).toContain("TextStyle get displayLarge");
    expect(output).toContain("TextStyle get bodyMedium");
  });

  test("uses asset provider by default", () => {
    const output = generateTheme(loadTokens(), "test_design");
    expect(output).toContain("fontFamily: 'Playfair Display'");
    expect(output).not.toContain("GoogleFonts");
  });
});

describe("generateBarrel", () => {
  test("exports all listed files", () => {
    const output = generateBarrel(["a.dart", "b.dart"]);
    expect(output).toContain("export 'a.dart';");
    expect(output).toContain("export 'b.dart';");
  });
});

describe("generatePackageBarrel", () => {
  test("exports theme path", () => {
    const output = generatePackageBarrel("test_pkg");
    expect(output).toContain("export 'core/theme/theme.dart';");
  });
});
