import { readFileSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, test } from "bun:test";

import { validateTokens } from "../../src/plugins/builtin/design/token-schema.js";
import type { ValidatedTokens } from "../../src/plugins/builtin/design/types.js";
import {
  generateBarrel,
  generateColorScheme,
  generateConstants,
  generatePackageBarrel,
  generateTheme,
  generateThemeExtensions,
} from "../../src/plugins/builtin/dart/token-codegen.js";

const FIXTURE_PATH = join(import.meta.dir, "..", "fixture-tokens", "tokens.json");

function loadTokens(): ValidatedTokens {
  const raw = JSON.parse(readFileSync(FIXTURE_PATH, "utf-8"));
  const result = validateTokens(raw);
  if (!result.data) {
    throw new Error("Fixture tokens invalid");
  }
  return result.data;
}

describe("generateColorScheme", () => {
  test("produces valid Dart with M3 color roles", () => {
    const output = generateColorScheme(loadTokens());
    expect(output).toContain("GENERATED BY MIDO");
    expect(output).toContain("abstract final class GeneratedColorScheme");
    expect(output).toContain("static ColorScheme get light");
    expect(output).toContain("static ColorScheme get dark");
    expect(output).toContain("primary:");
    expect(output).toContain("onPrimary:");
    expect(output).toContain("surface:");
    expect(output).toContain("Color(0xFF");
  });

  test("uses const ColorScheme constructor", () => {
    const output = generateColorScheme(loadTokens());
    expect(output).toContain("const ColorScheme.light(");
    expect(output).toContain("const ColorScheme.dark(");
  });

  test("only emits color roles present in tokens", () => {
    const output = generateColorScheme(loadTokens());
    // secondary is not in fixture
    expect(output).not.toContain("secondary:");
  });
});

describe("generateThemeExtensions", () => {
  test("produces @immutable classes with copyWith and lerp", () => {
    const output = generateThemeExtensions(loadTokens());
    expect(output).toContain("@immutable");
    expect(output).toContain("class AppColors extends ThemeExtension<AppColors>");
    expect(output).toContain("class GenreColors extends ThemeExtension<GenreColors>");
    expect(output).toContain("copyWith");
    expect(output).toContain("lerp");
    expect(output).toContain("Color.lerp");
  });

  test("generates static light and dark const instances", () => {
    const output = generateThemeExtensions(loadTokens());
    expect(output).toContain("static const light = AppColors(");
    expect(output).toContain("static const dark = AppColors(");
    expect(output).toContain("static const light = GenreColors(");
  });

  test("generates required named parameters in constructor", () => {
    const output = generateThemeExtensions(loadTokens());
    expect(output).toContain("required this.brand,");
    expect(output).toContain("required this.mystery,");
  });
});

describe("generateConstants", () => {
  test("generates DSSpacing, DSRadius, DSElevation, DSIconSize", () => {
    const output = generateConstants(loadTokens());
    expect(output).toContain("abstract final class DSSpacing");
    expect(output).toContain("abstract final class DSRadius");
    expect(output).toContain("abstract final class DSElevation");
    expect(output).toContain("abstract final class DSIconSize");
  });

  test("generates BorderRadius convenience constructors", () => {
    const output = generateConstants(loadTokens());
    expect(output).toContain("static const BorderRadius smAll");
    expect(output).toContain("BorderRadius.all(Radius.circular(sm))");
  });

  test("generates DSShadow with BoxShadow lists", () => {
    const output = generateConstants(loadTokens());
    expect(output).toContain("abstract final class DSShadow");
    expect(output).toContain("abstract final class DSShadowDark");
    expect(output).toContain("List<BoxShadow>");
    expect(output).toContain("BoxShadow(");
  });

  test("generates card shadow from shadowCard token", () => {
    const output = generateConstants(loadTokens());
    expect(output).toContain("static const List<BoxShadow> card");
  });
});

describe("generateTheme", () => {
  test("generates AppTheme with light/dark", () => {
    const output = generateTheme(loadTokens(), "test_design");
    expect(output).toContain("abstract final class AppTheme");
    expect(output).toContain("static final ThemeData light");
    expect(output).toContain("static final ThemeData dark");
  });

  test("generates ThemeContextExtension with getters", () => {
    const output = generateTheme(loadTokens(), "test_design");
    expect(output).toContain("extension ThemeContextExtension on BuildContext");
    expect(output).toContain("AppColors get appColors");
    // GenreColors has no _getter so it should use lowercase-first class name
    expect(output).toContain("GenreColors get genreColors");
  });

  test("generates text style shortcuts for scale entries", () => {
    const output = generateTheme(loadTokens(), "test_design");
    expect(output).toContain("TextStyle get displayLarge");
    expect(output).toContain("TextStyle get bodyMedium");
    expect(output).toContain("TextStyle get labelSmall");
  });

  test("uses asset provider (fontFamily in TextStyle)", () => {
    const output = generateTheme(loadTokens(), "test_design");
    expect(output).toContain("fontFamily: 'Merriweather'");
    expect(output).not.toContain("GoogleFonts");
  });

  test("includes ColorToHex extension", () => {
    const output = generateTheme(loadTokens(), "test_design");
    expect(output).toContain("extension ColorToHex on Color");
    expect(output).toContain("String get hex");
  });
});

describe("generateBarrel", () => {
  test("exports all listed files", () => {
    const output = generateBarrel(["a.dart", "b.dart"]);
    expect(output).toContain("export 'a.dart';");
    expect(output).toContain("export 'b.dart';");
  });
});

describe("generatePackageBarrel", () => {
  test("exports theme path", () => {
    const output = generatePackageBarrel("test_pkg");
    expect(output).toContain("export 'core/theme/theme.dart';");
  });
});
