export { loadConfig, type LoadedConfig } from "@/config/loader";
export {
  configSchema,
  DEFAULT_COMMIT_TYPES,
  DESIGN_FORMATS,
  HOOK_NAMES,
  type BridgeConfig,
  type CommitsConfig,
  type EcosystemConfig,
  type EnvConfig,
  type FormatConfig,
  type FormatDartConfig,
  type FormatGoConfig,
  type FormatPhpConfig,
  type FormatPythonConfig,
  type FormatRustConfig,
  type FormatTypescriptConfig,
  type HooksConfig,
  type LintConfig,
  type LintDartConfig,
  type LintGoConfig,
  type LintPhpConfig,
  type LintPythonConfig,
  type LintRustConfig,
  type LintTypescriptConfig,
  type NeutronConfig,
} from "@/config/schema";
