import type {
  ExtensionFieldType,
  ResolvedExtensionField,
  ValidatedTokens,
} from "../design/types.js";
import { resolveExtensions } from "../design/types.js";

const HEADER = `// GENERATED BY MIDO — DO NOT EDIT`;

/**
 * Convert a 6-char hex string (#RRGGBB) to a Dart Color constructor.
 */
function hexToDartColor(hex: string): string {
  const clean = hex.replace("#", "").toUpperCase();
  return `Color(0xFF${clean})`;
}

/**
 * Encode a hex color with a separate opacity into a single 0xAARRGGBB Dart Color.
 */
function shadowToDartColor(color: string, opacity: number): string {
  const clean = color.replace("#", "").toUpperCase();
  const alpha = Math.round(opacity * 255)
    .toString(16)
    .padStart(2, "0")
    .toUpperCase();
  return `Color(0x${alpha}${clean})`;
}

/**
 * Get the Dart lerp expression for a given extension field type.
 */
function lerpExpr(fieldName: string, type: ExtensionFieldType): string {
  switch (type) {
    case "color":
    case "color-static":
      return `Color.lerp(${fieldName}, other.${fieldName}, t)!`;
    case "number":
    case "number-themed":
      return `lerpDouble(${fieldName}, other.${fieldName}, t)!`;
    case "string":
      return `t < 0.5 ? ${fieldName} : other.${fieldName}`;
  }
}

/**
 * Get the Dart type for a given extension field type.
 */
function dartType(type: ExtensionFieldType): string {
  switch (type) {
    case "color":
    case "color-static":
      return "Color";
    case "number":
    case "number-themed":
      return "double";
    case "string":
      return "String";
  }
}

/**
 * Get the light-mode Dart value for an extension field.
 */
function dartLightValue(field: ResolvedExtensionField): string {
  switch (field.type) {
    case "color": {
      const v = field.value as { readonly light: string; readonly dark: string };
      return hexToDartColor(v.light);
    }
    case "color-static":
      return hexToDartColor(field.value as string);
    case "number":
      return `${field.value as number}`;
    case "number-themed": {
      const v = field.value as { readonly light: number; readonly dark: number };
      return `${v.light}`;
    }
    case "string":
      return `'${field.value as string}'`;
  }
}

/**
 * Get the dark-mode Dart value for an extension field.
 */
function dartDarkValue(field: ResolvedExtensionField): string {
  switch (field.type) {
    case "color": {
      const v = field.value as { readonly light: string; readonly dark: string };
      return hexToDartColor(v.dark);
    }
    case "color-static":
      return hexToDartColor(field.value as string);
    case "number":
      return `${field.value as number}`;
    case "number-themed": {
      const v = field.value as { readonly light: number; readonly dark: number };
      return `${v.dark}`;
    }
    case "string":
      return `'${field.value as string}'`;
  }
}

// ─── M3 ColorScheme fields (Flutter 3.18+) ─────────────────────────────────

const COLOR_SCHEME_FIELDS: readonly string[] = [
  "primary",
  "onPrimary",
  "primaryContainer",
  "onPrimaryContainer",
  "primaryFixed",
  "primaryFixedDim",
  "onPrimaryFixed",
  "onPrimaryFixedVariant",
  "secondary",
  "onSecondary",
  "secondaryContainer",
  "onSecondaryContainer",
  "secondaryFixed",
  "secondaryFixedDim",
  "onSecondaryFixed",
  "onSecondaryFixedVariant",
  "tertiary",
  "onTertiary",
  "tertiaryContainer",
  "onTertiaryContainer",
  "tertiaryFixed",
  "tertiaryFixedDim",
  "onTertiaryFixed",
  "onTertiaryFixedVariant",
  "surface",
  "onSurface",
  "onSurfaceVariant",
  "surfaceDim",
  "surfaceBright",
  "surfaceTint",
  "surfaceContainerLowest",
  "surfaceContainerLow",
  "surfaceContainer",
  "surfaceContainerHigh",
  "surfaceContainerHighest",
  "error",
  "onError",
  "errorContainer",
  "onErrorContainer",
  "outline",
  "outlineVariant",
  "inverseSurface",
  "onInverseSurface",
  "inversePrimary",
  "shadow",
  "scrim",
];

// ─── Generators ────────────────────────────────────────────────────────────

/**
 * Generate the M3 ColorScheme Dart file.
 * Only emits color roles that exist in tokens.color.
 */
export function generateColorScheme(tokens: ValidatedTokens): string {
  const lines: string[] = [HEADER, "", "import 'package:flutter/material.dart';", ""];

  lines.push("abstract final class GeneratedColorScheme {");

  for (const mode of ["light", "dark"] as const) {
    lines.push(`  static ColorScheme get ${mode} => const ColorScheme.${mode}(`);

    for (const field of COLOR_SCHEME_FIELDS) {
      const entry = tokens.color[field];
      if (!entry) {
        continue;
      }
      lines.push(`    ${field}: ${hexToDartColor(entry[mode])},`);
    }

    lines.push("  );");
    if (mode === "light") {
      lines.push("");
    }
  }

  lines.push("}");
  lines.push("");
  return lines.join("\n");
}

/**
 * Generate ThemeExtension classes — one per extensions entry.
 * Includes: @immutable, const constructor, final fields, static light/dark,
 * copyWith, lerp with type-appropriate function.
 */
export function generateThemeExtensions(tokens: ValidatedTokens): string {
  const extensions = resolveExtensions(tokens.extensions);
  if (extensions.length === 0) {
    return `${HEADER}\n\n// No extensions defined in tokens.json\n`;
  }

  const lines: string[] = [
    HEADER,
    "",
    "import 'dart:ui';",
    "",
    "import 'package:flutter/material.dart';",
    "",
  ];

  let needsLerpDouble = false;
  for (const ext of extensions) {
    for (const [, field] of ext.fields) {
      if (field.type === "number" || field.type === "number-themed") {
        needsLerpDouble = true;
      }
    }
  }

  if (needsLerpDouble) {
    // lerpDouble is in dart:ui, already imported above
  }

  let extIndex = 0;
  for (const ext of extensions) {
    const fields = [...ext.fields.values()];

    // Class declaration
    lines.push("@immutable");
    lines.push(`class ${ext.name} extends ThemeExtension<${ext.name}> {`);

    // Constructor
    lines.push(`  const ${ext.name}({`);
    for (const field of fields) {
      lines.push(`    required this.${field.name},`);
    }
    lines.push("  });");
    lines.push("");

    // Fields
    for (const field of fields) {
      lines.push(`  final ${dartType(field.type)} ${field.name};`);
    }
    lines.push("");

    // Static light
    lines.push(`  static const light = ${ext.name}(`);
    for (const field of fields) {
      lines.push(`    ${field.name}: ${dartLightValue(field)},`);
    }
    lines.push("  );");
    lines.push("");

    // Static dark
    lines.push(`  static const dark = ${ext.name}(`);
    for (const field of fields) {
      lines.push(`    ${field.name}: ${dartDarkValue(field)},`);
    }
    lines.push("  );");
    lines.push("");

    // copyWith
    lines.push("  @override");
    lines.push(`  ${ext.name} copyWith({`);
    for (const field of fields) {
      lines.push(`    ${dartType(field.type)}? ${field.name},`);
    }
    lines.push("  }) {");
    lines.push(`    return ${ext.name}(`);
    for (const field of fields) {
      lines.push(`      ${field.name}: ${field.name} ?? this.${field.name},`);
    }
    lines.push("    );");
    lines.push("  }");
    lines.push("");

    // lerp
    lines.push("  @override");
    lines.push(`  ${ext.name} lerp(${ext.name}? other, double t) {`);
    lines.push(`    if (other is! ${ext.name}) return this;`);
    lines.push(`    return ${ext.name}(`);
    for (const field of fields) {
      lines.push(`      ${field.name}: ${lerpExpr(field.name, field.type)},`);
    }
    lines.push("    );");
    lines.push("  }");
    lines.push("}");

    extIndex++;
    if (extIndex < extensions.length) {
      lines.push("");
    }
  }

  lines.push("");
  return lines.join("\n");
}

/**
 * Generate constants: DSSpacing, DSRadius, DSElevation, DSIconSize, DSShadow.
 */
export function generateConstants(tokens: ValidatedTokens): string {
  const lines: string[] = [HEADER, "", "import 'package:flutter/material.dart';", ""];

  // DSSpacing
  if (tokens.spacing) {
    lines.push("abstract final class DSSpacing {");
    for (const [key, value] of Object.entries(tokens.spacing)) {
      lines.push(`  static const double ${key} = ${value};`);
    }
    lines.push("}");
    lines.push("");
  }

  // DSRadius
  if (tokens.radius) {
    lines.push("abstract final class DSRadius {");
    for (const [key, value] of Object.entries(tokens.radius)) {
      lines.push(`  static const double ${key} = ${value};`);
    }
    lines.push("");
    lines.push("  // Convenience BorderRadius constructors");
    for (const [key, value] of Object.entries(tokens.radius)) {
      if (value <= 0) {
        continue;
      }
      lines.push(
        `  static const BorderRadius ${key}All = BorderRadius.all(Radius.circular(${key}));`,
      );
    }
    lines.push("}");
    lines.push("");
  }

  // DSElevation
  if (tokens.elevation) {
    lines.push("abstract final class DSElevation {");
    for (const [key, entry] of Object.entries(tokens.elevation)) {
      lines.push(`  static const double ${key} = ${entry.dp};`);
    }
    lines.push("}");
    lines.push("");
  }

  // DSIconSize
  if (tokens.iconSize) {
    lines.push("abstract final class DSIconSize {");
    for (const [key, value] of Object.entries(tokens.iconSize)) {
      lines.push(`  static const double ${key} = ${value};`);
    }
    lines.push("}");
    lines.push("");
  }

  // DSShadow (light) + DSShadowDark (dark) — from elevation entries
  if (tokens.elevation) {
    for (const mode of ["light", "dark"] as const) {
      const className = mode === "light" ? "DSShadow" : "DSShadowDark";
      lines.push(`abstract final class ${className} {`);

      // shadowCard standalone
      if (tokens.shadowCard) {
        const shadows = tokens.shadowCard[mode];
        lines.push("  static const List<BoxShadow> card = [");
        for (const s of shadows) {
          lines.push("    BoxShadow(");
          lines.push(`      offset: Offset(${s.x}, ${s.y}),`);
          lines.push(`      blurRadius: ${s.blur},`);
          lines.push(`      spreadRadius: ${s.spread},`);
          lines.push(`      color: ${shadowToDartColor(s.color, s.opacity)},`);
          lines.push("    ),");
        }
        lines.push("  ];");
        lines.push("");
      }

      // Elevation shadows
      for (const [key, entry] of Object.entries(tokens.elevation)) {
        const shadows = entry.shadow[mode];
        lines.push(`  static const List<BoxShadow> ${key} = [`);
        for (const s of shadows) {
          lines.push("    BoxShadow(");
          lines.push(`      offset: Offset(${s.x}, ${s.y}),`);
          lines.push(`      blurRadius: ${s.blur},`);
          lines.push(`      spreadRadius: ${s.spread},`);
          lines.push(`      color: ${shadowToDartColor(s.color, s.opacity)},`);
          lines.push("    ),");
        }
        lines.push("  ];");
      }

      lines.push("}");
      lines.push("");
    }
  }

  return lines.join("\n");
}

/**
 * Generate the ThemeData assembly file.
 * Includes: AppTheme with light/dark, text theme builder, context extension,
 * ColorToHex extension. Font provider-aware.
 */
export function generateTheme(tokens: ValidatedTokens, packageName: string): string {
  const extensions = resolveExtensions(tokens.extensions);
  const typo = tokens.typography;
  const provider = typo?.provider ?? "asset";

  const lines: string[] = [HEADER, ""];

  // Imports
  lines.push("import 'package:flutter/material.dart';");
  if (provider === "google_fonts") {
    lines.push("import 'package:google_fonts/google_fonts.dart';");
  }
  lines.push(`import 'package:${packageName}/core/theme/generated/generated.dart';`);
  lines.push("");

  // Re-export generated barrel
  lines.push(`export 'package:${packageName}/core/theme/generated/generated.dart';`);
  lines.push("");

  // ThemeContextExtension
  lines.push("extension ThemeContextExtension on BuildContext {");
  lines.push("  ColorScheme get colorScheme => Theme.of(this).colorScheme;");
  lines.push("  TextTheme get textTheme => Theme.of(this).textTheme;");

  for (const ext of extensions) {
    lines.push(`  ${ext.name} get ${ext.getter} => Theme.of(this).extension<${ext.name}>()!;`);
  }

  // Text style shortcuts
  if (typo?.scale) {
    lines.push("");
    for (const key of Object.keys(typo.scale)) {
      lines.push(`  TextStyle get ${key} => textTheme.${key}!;`);
    }
  }

  lines.push("}");
  lines.push("");

  // ColorToHex extension
  lines.push("extension ColorToHex on Color {");
  lines.push("  String get hex {");
  lines.push("    final r = (this.r * 255).round().toRadixString(16).padLeft(2, '0');");
  lines.push("    final g = (this.g * 255).round().toRadixString(16).padLeft(2, '0');");
  lines.push("    final b = (this.b * 255).round().toRadixString(16).padLeft(2, '0');");
  lines.push("    return '#$r$g$b';");
  lines.push("  }");
  lines.push("}");
  lines.push("");

  // AppTheme class
  lines.push("abstract final class AppTheme {");

  // Light and dark factory calls
  const extArgs = extensions.map((e) => `    ${e.name}.light,`).join("\n");
  const extArgsDark = extensions.map((e) => `    ${e.name}.dark,`).join("\n");

  lines.push("  static final ThemeData light = _build(");
  lines.push("    GeneratedColorScheme.light,");
  if (extArgs) {
    lines.push(extArgs);
  }
  lines.push("  );");
  lines.push("");
  lines.push("  static final ThemeData dark = _build(");
  lines.push("    GeneratedColorScheme.dark,");
  if (extArgsDark) {
    lines.push(extArgsDark);
  }
  lines.push("  );");
  lines.push("");

  // _build method
  const extParams = extensions.map((e) => `    ${e.name} ${e.getter},`).join("\n");
  lines.push("  static ThemeData _build(");
  lines.push("    ColorScheme scheme,");
  if (extParams) {
    lines.push(extParams);
  }
  lines.push("  ) {");
  lines.push("    return ThemeData(");
  lines.push("      useMaterial3: true,");
  lines.push("      brightness: scheme.brightness,");
  lines.push("      colorScheme: scheme,");
  lines.push("      scaffoldBackgroundColor: scheme.surface,");

  // extensions list
  if (extensions.length > 0) {
    const extList = extensions.map((e) => e.getter).join(", ");
    lines.push(`      extensions: [${extList}],`);
  }

  // fontFamily
  if (typo?.fontFamily) {
    const body = typo.fontFamily["body"];
    if (body) {
      lines.push(`      fontFamily: '${body}',`);
    }
  }

  lines.push("      textTheme: _buildTextTheme(scheme),");
  lines.push("    );");
  lines.push("  }");
  lines.push("");

  // _buildTextTheme
  lines.push("  static TextTheme _buildTextTheme(ColorScheme scheme) {");
  lines.push("    return TextTheme(");

  if (typo?.scale) {
    for (const [key, entry] of Object.entries(typo.scale)) {
      const familyKey = entry.family;
      const familyName = typo.fontFamily[familyKey] ?? familyKey;
      const weightKey = entry.weight;
      const weightValue = typo.fontWeight[weightKey] ?? 400;
      const dartWeight = `FontWeight.w${weightValue}`;

      let textStyleExpr: string;
      if (provider === "google_fonts") {
        const methodName = familyName
          .split(" ")
          .map((w, i) => (i === 0 ? w.toLowerCase() : w.charAt(0).toUpperCase() + w.slice(1)))
          .join("");
        textStyleExpr = `GoogleFonts.${methodName}(\n        fontSize: ${entry.size},\n        fontWeight: ${dartWeight},\n        color: scheme.onSurface,\n      )`;
      } else if (provider === "asset") {
        textStyleExpr = `TextStyle(\n        fontFamily: '${familyName}',\n        fontSize: ${entry.size},\n        fontWeight: ${dartWeight},\n        color: scheme.onSurface,\n      )`;
      } else {
        textStyleExpr = `TextStyle(\n        fontSize: ${entry.size},\n        fontWeight: ${dartWeight},\n        color: scheme.onSurface,\n      )`;
      }

      lines.push(`      ${key}: ${textStyleExpr},`);
    }
  }

  lines.push("    );");
  lines.push("  }");
  lines.push("}");
  lines.push("");

  return lines.join("\n");
}

/**
 * Generate a barrel file that re-exports all generated files.
 */
export function generateBarrel(fileNames: readonly string[]): string {
  const lines: string[] = [HEADER, ""];
  for (const name of fileNames) {
    lines.push(`export '${name}';`);
  }
  lines.push("");
  return lines.join("\n");
}

/**
 * Generate the top-level package barrel file.
 */
export function generatePackageBarrel(_packageName: string): string {
  const lines: string[] = [HEADER, ""];
  lines.push(`export 'core/theme/theme.dart';`);
  lines.push("");
  return lines.join("\n");
}
