import { packageJsonParser } from './parsers/package-json.js';
import { pubspecParser } from './parsers/pubspec.js';
import type { ManifestParser } from './parsers/types.js';
import { printBanner } from './banner.js';
import { VERSION } from './version.js';

// Parser registry — add new ecosystem parsers here
const parsers = new Map<string, ManifestParser>([
  [packageJsonParser.manifestName, packageJsonParser],
  [pubspecParser.manifestName, pubspecParser],
]);

const HELP = `
mido — cross-ecosystem monorepo workspace tool

Usage:
  mido <command> [options]

Commands:
  init              Scan repo and generate mido.yml
  install           Install git hooks
  check             Run all workspace consistency checks
  check --fix       Interactively resolve version mismatches and update mido.lock
  check --quiet     Silent mode — only output on failure (for hooks)
  dev               Watch bridges and regenerate on changes
  commit-msg <file> Validate a commit message (used by git hooks)
  help              Show this help message

Config:
  mido.yml          Workspace config (searched upward from cwd)
  mido.lock         Resolved version policy (auto-generated by --fix)

Options:
  --help, -h       Show help
  --version, -v    Show version
`;


async function main(): Promise<void> {
  const args = process.argv.slice(2);
  const command = args[0];

  if (!command || command === 'help' || command === '--help' || command === '-h') {
    printBanner();
    console.log(HELP);
    process.exit(0);
  }

  if (command === '--version' || command === '-v') {
    console.log(VERSION);
    process.exit(0);
  }

  if (command === 'check') {
    const fix = args.includes('--fix');
    const quiet = args.includes('--quiet') || args.includes('--hook');
    const { runCheck } = await import('./commands/check.js');
    const exitCode = await runCheck(parsers, { fix, quiet });
    process.exit(exitCode);
  }

  if (command === 'init') {
    const { runInit } = await import('./commands/init.js');
    const exitCode = await runInit(process.cwd(), parsers);
    process.exit(exitCode);
  }

  if (command === 'dev') {
    const { runDev } = await import('./watcher/dev.js');
    const exitCode = await runDev(parsers);
    process.exit(exitCode);
  }

  if (command === 'install') {
    const { runInstall } = await import('./commands/install.js');
    const exitCode = await runInstall(process.cwd());
    process.exit(exitCode);
  }

  if (command === 'commit-msg') {
    const filePath = args[1];
    if (!filePath) {
      console.error('Usage: mido commit-msg <file>');
      process.exit(1);
    }
    const { runCommitMsg } = await import('./commands/commit-msg.js');
    const exitCode = await runCommitMsg(filePath);
    process.exit(exitCode);
  }

  console.error(`Unknown command: ${command}\nRun "mido help" for usage.`);
  process.exit(1);
}

main().catch((error: unknown) => {
  const message = error instanceof Error ? error.message : String(error);
  console.error(`\x1b[31merror:\x1b[0m ${message}`);
  process.exit(1);
});
