import { packageJsonParser } from "./parsers/package-json.js";
import { pubspecParser } from "./parsers/pubspec.js";
import type { ManifestParser } from "./parsers/types.js";
import { printBanner } from "./banner.js";
import { RED, RESET } from "./output.js";
import { VERSION } from "./version.js";

// Parser registry — add new ecosystem parsers here
const parsers = new Map<string, ManifestParser>([
  [packageJsonParser.manifestName, packageJsonParser],
  [pubspecParser.manifestName, pubspecParser],
]);

/** Extract the value following a --flag from the args list */
function getFlagValue(args: readonly string[], flag: string): string | undefined {
  const idx = args.indexOf(flag);
  if (idx === -1 || idx + 1 >= args.length) {
    return undefined;
  }
  return args[idx + 1];
}

const HELP = `
mido — cross-ecosystem monorepo workspace tool

Usage:
  mido <command> [options]

Setup:
  init              Scan repo, generate mido.yml, install hooks
  install           Write git hooks to .git/hooks/
  add               Scaffold a new package in the workspace

Development:
  dev [--verbose]   Watch bridges and regenerate on changes
  generate          Run all bridge pipelines (--force to skip cache)
  lint [--fix]      Run linters across all packages
  fmt [--check]     Format all packages
  test              Run tests across all packages
  build [--all]     Build library packages (--all includes apps)

Workspace health:
  check [--fix]     Version consistency, bridge validation, env parity
  doctor            Diagnostic: config, hooks, tools, generated output
  outdated          Check for newer dependency versions
  why <dep>         Show which packages use a dependency
  graph             Interactive D3.js dependency graph (--dot, --ascii)

CI / automation:
  ci                Full pipeline: generate → build → lint → test → check
  affected          Packages affected by changes (--base <ref>, --json)
  pre-commit        Format check + lint + workspace check
  commit-msg <file> Validate conventional commit message

Common flags:
  --quiet              Only show failures
  --package <path>     Target a specific package
  --ecosystem <name>   Target a specific ecosystem (lint, fmt, test)
  --json               Machine-readable output (affected, outdated, why)

Config:
  mido.yml          Workspace config (searched upward from cwd)
  mido.lock         Resolved version policy (auto-generated by --fix)

Options:
  --help, -h       Show help
  --version, -v    Show version
`;

async function main(): Promise<void> {
  const args = process.argv.slice(2);
  const command = args[0];

  if (!command || command === "help" || command === "--help" || command === "-h") {
    printBanner();
    console.log(HELP);
    process.exit(0);
  }

  if (command === "--version" || command === "-v") {
    console.log(VERSION);
    process.exit(0);
  }

  if (command === "affected") {
    const base = getFlagValue(args, "--base");
    const json = args.includes("--json");
    const { runAffected } = await import("./commands/affected.js");
    const exitCode = await runAffected(parsers, { base, json });
    process.exit(exitCode);
  }

  if (command === "check") {
    const fix = args.includes("--fix");
    const quiet = args.includes("--quiet") || args.includes("--hook");
    const { runCheck } = await import("./commands/check.js");
    const exitCode = await runCheck(parsers, { fix, quiet });
    process.exit(exitCode);
  }

  if (command === "add") {
    const { runAdd } = await import("./commands/add.js");
    const exitCode = await runAdd();
    process.exit(exitCode);
  }

  if (command === "init") {
    const { runInit } = await import("./commands/init.js");
    const exitCode = await runInit(process.cwd(), parsers);
    process.exit(exitCode);
  }

  if (command === "graph") {
    const format = args.includes("--dot") ? "dot" : args.includes("--ascii") ? "ascii" : "html";
    const noOpen = args.includes("--no-open");
    const { runGraph } = await import("./commands/graph.js");
    const exitCode = await runGraph(parsers, { format, open: !noOpen });
    process.exit(exitCode);
  }

  if (command === "doctor") {
    const { runDoctor } = await import("./commands/doctor.js");
    const exitCode = await runDoctor(parsers);
    process.exit(exitCode);
  }

  if (command === "dev") {
    const verbose = args.includes("--verbose");
    const { runDev } = await import("./watcher/dev.js");
    const exitCode = await runDev(parsers, { verbose });
    process.exit(exitCode);
  }

  if (command === "install") {
    const { runInstall } = await import("./commands/install.js");
    const exitCode = await runInstall(process.cwd());
    process.exit(exitCode);
  }

  if (command === "lint") {
    const fix = args.includes("--fix");
    const quiet = args.includes("--quiet");
    const pkg = getFlagValue(args, "--package");
    const ecosystem = getFlagValue(args, "--ecosystem");
    const { runLint } = await import("./commands/lint.js");
    const exitCode = await runLint(parsers, { fix, quiet, package: pkg, ecosystem });
    process.exit(exitCode);
  }

  if (command === "fmt") {
    const check = args.includes("--check");
    const quiet = args.includes("--quiet");
    const pkg = getFlagValue(args, "--package");
    const ecosystem = getFlagValue(args, "--ecosystem");
    const { runFmt } = await import("./commands/fmt.js");
    const exitCode = await runFmt(parsers, { check, quiet, package: pkg, ecosystem });
    process.exit(exitCode);
  }

  if (command === "generate") {
    const quiet = args.includes("--quiet");
    const verbose = args.includes("--verbose");
    const force = args.includes("--force");
    const { runGenerate } = await import("./commands/generate.js");
    const exitCode = await runGenerate(parsers, { quiet, verbose, force });
    process.exit(exitCode);
  }

  if (command === "outdated") {
    const json = args.includes("--json");
    const { runOutdated } = await import("./commands/outdated.js");
    const exitCode = await runOutdated(parsers, { json });
    process.exit(exitCode);
  }

  if (command === "test") {
    const quiet = args.includes("--quiet");
    const pkg = getFlagValue(args, "--package");
    const ecosystem = getFlagValue(args, "--ecosystem");
    const { runTest } = await import("./commands/test.js");
    const exitCode = await runTest(parsers, { quiet, package: pkg, ecosystem });
    process.exit(exitCode);
  }

  if (command === "build") {
    const quiet = args.includes("--quiet");
    const all = args.includes("--all");
    const pkg = getFlagValue(args, "--package");
    const { runBuild } = await import("./commands/build.js");
    const exitCode = await runBuild(parsers, { quiet, all, package: pkg });
    process.exit(exitCode);
  }

  if (command === "ci") {
    const verbose = args.includes("--verbose");
    const { runCi } = await import("./commands/ci.js");
    const exitCode = await runCi(parsers, { verbose });
    process.exit(exitCode);
  }

  if (command === "pre-commit") {
    const { runPreCommit } = await import("./commands/pre-commit.js");
    const exitCode = await runPreCommit(parsers);
    process.exit(exitCode);
  }

  if (command === "commit-msg") {
    const filePath = args[1];
    if (!filePath) {
      console.error("Usage: mido commit-msg <file>");
      process.exit(1);
    }
    const { runCommitMsg } = await import("./commands/commit-msg.js");
    const exitCode = await runCommitMsg(filePath);
    process.exit(exitCode);
  }

  if (command === "why") {
    const depName = args[1];
    if (!depName) {
      console.error("Usage: mido why <dependency>");
      process.exit(1);
    }
    const json = args.includes("--json");
    const { runWhy } = await import("./commands/why.js");
    const exitCode = await runWhy(parsers, depName, { json });
    process.exit(exitCode);
  }

  console.error(`Unknown command: ${command}\nRun "mido help" for usage.`);
  process.exit(1);
}

main().catch((error: unknown) => {
  // CancelError from @clack/prompts cancel flow — exit cleanly
  if (error instanceof Error && error.name === "CancelError") {
    process.exit(0);
  }
  const message = error instanceof Error ? error.message : String(error);
  console.error(`${RED}error:${RESET} ${message}`);
  process.exit(1);
});
