import { createHash } from "node:crypto";
import { existsSync } from "node:fs";
import { readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";

import { parse as parseYaml, stringify as stringifyYaml } from "yaml";
import { z } from "zod";

import { BINARY_NAME, LOCK_FILENAME } from "@/branding";

const LOCK_VERSION = 2;

const LOCK_HEADER = `# Auto-generated by ${BINARY_NAME} check --fix
# This file is the source of truth for cross-package version policy.
# Commit this file to version control.
`;

// ─── Schema ────────────────────────────────────────────────────────────────

/** V2 lock entry: range + metadata */
const lockEntrySchema = z.object({
  /** The agreed-upon version range (e.g., "^3.25.67") */
  range: z.string(),
  /** SHA-256 hash of the range string for tamper detection */
  integrity: z.string(),
  /** Ecosystems where this dependency appears */
  ecosystems: z.array(z.string()).min(1),
  /** ISO 8601 timestamp when this entry was resolved */
  resolvedAt: z.string(),
});

const lockSchemaV2 = z.object({
  version: z.literal(LOCK_VERSION),
  resolved: z.record(z.string(), lockEntrySchema),
});

/** V1 lock schema (flat range strings) — for migration */
const lockSchemaV1 = z.object({
  resolved: z.record(z.string(), z.string()),
});

export type LockEntry = z.infer<typeof lockEntrySchema>;
export type MidoLock = z.infer<typeof lockSchemaV2>;

// ─── Integrity ─────────────────────────────────────────────────────────────

/** Compute SHA-256 integrity hash for a range string */
function computeIntegrity(range: string): string {
  return `sha256-${createHash("sha256").update(range).digest("hex").slice(0, 16)}`;
}

/** Verify a lock entry's integrity hash matches its range */
export function verifyIntegrity(entry: LockEntry): boolean {
  return entry.integrity === computeIntegrity(entry.range);
}

// ─── Migration ─────────────────────────────────────────────────────────────

/** Migrate a V1 lock (flat ranges) to V2 (structured entries) */
function migrateV1toV2(v1: z.infer<typeof lockSchemaV1>): MidoLock {
  const now = new Date().toISOString();
  const resolved: Record<string, LockEntry> = {};

  for (const [name, range] of Object.entries(v1.resolved)) {
    resolved[name] = {
      range,
      integrity: computeIntegrity(range),
      ecosystems: ["unknown"],
      resolvedAt: now,
    };
  }

  return { version: LOCK_VERSION, resolved };
}

// ─── Read / Write ──────────────────────────────────────────────────────────

export async function loadLock(root: string): Promise<MidoLock | null> {
  const lockPath = join(root, LOCK_FILENAME);
  if (!existsSync(lockPath)) {
    return null;
  }

  try {
    const raw = await readFile(lockPath, "utf-8");
    const parsed: unknown = parseYaml(raw);

    // Try V2 first
    const v2Result = lockSchemaV2.safeParse(parsed);
    if (v2Result.success) {
      return v2Result.data;
    }

    // Try V1 migration
    const v1Result = lockSchemaV1.safeParse(parsed);
    if (v1Result.success) {
      const migrated = migrateV1toV2(v1Result.data);
      // Write migrated lock back to disk
      await writeLock(root, migrated);
      return migrated;
    }

    return null;
  } catch {
    return null;
  }
}

export async function writeLock(root: string, lock: MidoLock): Promise<void> {
  const lockPath = join(root, LOCK_FILENAME);

  // Sort keys alphabetically for stable diffs
  const sorted: Record<string, LockEntry> = {};
  for (const key of Object.keys(lock.resolved).sort()) {
    const entry = lock.resolved[key];
    if (!entry) {
      continue;
    }
    sorted[key] = entry;
  }

  const body = stringifyYaml({ version: LOCK_VERSION, resolved: sorted });
  await writeFile(lockPath, LOCK_HEADER + "\n" + body, "utf-8");
}

// ─── Merge ─────────────────────────────────────────────────────────────────

export interface LockUpdate {
  readonly depName: string;
  readonly range: string;
  readonly ecosystems: readonly string[];
}

export function mergeLock(existing: MidoLock | null, updates: readonly LockUpdate[]): MidoLock {
  const resolved: Record<string, LockEntry> = { ...existing?.resolved };
  const now = new Date().toISOString();

  for (const update of updates) {
    const existingEntry = resolved[update.depName];
    const mergedEcosystems = existingEntry
      ? [...new Set([...existingEntry.ecosystems, ...update.ecosystems])]
      : [...update.ecosystems];

    resolved[update.depName] = {
      range: update.range,
      integrity: computeIntegrity(update.range),
      ecosystems: mergedEcosystems,
      resolvedAt: now,
    };
  }

  return { version: LOCK_VERSION, resolved };
}

// ─── Query ─────────────────────────────────────────────────────────────────

/** Get the locked range for a dependency, or undefined if not locked */
export function getLockedRange(lock: MidoLock, depName: string): string | undefined {
  return lock.resolved[depName]?.range;
}

/**
 * Fill in "unknown" ecosystems from the workspace graph.
 * Called after loading a V1-migrated lock to resolve ecosystem info
 * from the actual dependency data in the workspace.
 */
export function enrichEcosystems(
  lock: MidoLock,
  depEcosystems: ReadonlyMap<string, readonly string[]>,
): MidoLock {
  let changed = false;
  const resolved: Record<string, LockEntry> = {};

  for (const [name, entry] of Object.entries(lock.resolved)) {
    const hasUnknown = entry.ecosystems.length === 1 && entry.ecosystems[0] === "unknown";
    const known = depEcosystems.get(name);

    if (hasUnknown && known && known.length > 0) {
      resolved[name] = { ...entry, ecosystems: [...known] };
      changed = true;
    } else {
      resolved[name] = entry;
    }
  }

  return changed ? { version: lock.version, resolved } : lock;
}

/** Check all entries for integrity violations */
export function checkIntegrity(lock: MidoLock): readonly string[] {
  const violations: string[] = [];
  for (const [name, entry] of Object.entries(lock.resolved)) {
    if (!verifyIntegrity(entry)) {
      violations.push(name);
    }
  }
  return violations;
}
