import { readFile, writeFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import { join } from "node:path";

import { parse as parseYaml, stringify as stringifyYaml } from "yaml";
import { z } from "zod";

const LOCK_FILENAME = "mido.lock";

const LOCK_HEADER = `# Auto-generated by mido check --fix
# This file is the source of truth for cross-package version policy.
# Commit this file to version control.
`;

const lockSchema = z.object({
  resolved: z.record(z.string(), z.string()),
});

export type MidoLock = z.infer<typeof lockSchema>;

export async function loadLock(root: string): Promise<MidoLock | null> {
  const lockPath = join(root, LOCK_FILENAME);
  if (!existsSync(lockPath)) {
    return null;
  }

  try {
    const raw = await readFile(lockPath, "utf-8");
    const parsed = parseYaml(raw);
    const result = lockSchema.safeParse(parsed);
    return result.success ? result.data : null;
  } catch {
    return null;
  }
}

export async function writeLock(root: string, lock: MidoLock): Promise<void> {
  const lockPath = join(root, LOCK_FILENAME);

  // Sort keys alphabetically for stable diffs
  const sorted: Record<string, string> = {};
  for (const key of Object.keys(lock.resolved).sort()) {
    const value = lock.resolved[key];
    if (!value) {
      continue;
    }
    sorted[key] = value;
  }

  const body = stringifyYaml({ resolved: sorted });
  await writeFile(lockPath, LOCK_HEADER + "\n" + body, "utf-8");
}

export function mergeLock(existing: MidoLock | null, updates: Record<string, string>): MidoLock {
  const resolved = { ...existing?.resolved, ...updates };
  return { resolved };
}
